authentication/urls.py
from django.urls import path

from .views import (register_librarian, register_member,
                    login_user, logout_user)

app_name = 'authentication'
urlpatterns = [
    path('register-librarian/', register_librarian, name='register-librarian'),
    path('register-member/', register_member, name='register-member'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

dashboard/urls.py
from django.urls import path

from .views.general import home, browse_books
from .views.author import AuthorCreateView, list_authors, AuthorUpdateView, delete_author
from .views.publisher import PublisherCreateView, list_publishers, PublisherUpdateView, delete_publisher
from .views.category import CategoryCreateView, list_categories, CategoryUpdateView, delete_category
from .views.book import create_book, list_books, book_detail, update_book, delete_book
from .views.issue import issue_book, list_issues, return_issued_book
from .views.fine import list_fines
from .views.book_request import request_book, list_book_requests
from .views.member import members_list, member_info, member_report

app_name = 'dashboard'
urlpatterns = [
    # Dashboard home
    path('home/', home, name='home'),
    path('browse/', browse_books, name='browse'),
    # Authors
    path('authors/', list_authors, name='list-authors'),
    path('authors/new/', AuthorCreateView.as_view(), name='create-author'),
    path('authors/<int:pk>/update/',
         AuthorUpdateView.as_view(), name='update-author'),
    path('authors/<int:pk>/delete/',
         delete_author, name='delete-author'),
    # Publishers
    path('publishers/', list_publishers, name='list-publishers'),
    path('publishers/new/', PublisherCreateView.as_view(), name='create-publisher'),
    path('publishers/<int:pk>/update/',
         PublisherUpdateView.as_view(), name='update-publisher'),
    path('publishers/<int:pk>/delete/',
         delete_publisher, name='delete-publisher'),
    # Categories
    path('categories/', list_categories, name='list-categories'),
    path('categories/new/', CategoryCreateView.as_view(), name='create-category'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='update-category'),
    path('categories/<int:pk>/delete/',
         delete_category, name='delete-category'),
    # Books
    path('books/', list_books, name='list-books'),
    path('books/new/', create_book, name='create-book'),
    path('books/<int:pk>/', book_detail, name='book-detail'),
    path('books/<int:pk>/update/', update_book, name='update-book'),
    path('books/<int:pk>/delete/', delete_book, name='delete-book'),
    # Issue
    path('issues/', list_issues, name='list-issues'),
    path('issues/new/', issue_book, name='create-issue'),
    path('issues/<int:pk>/return/', return_issued_book, name='return-issued'),
    # Fines
    path('fines/', list_fines, name='list-fines'),
    # Book Requests
    path('books/requests/', list_book_requests, name='book-requests'),
    path('books/requests/<int:pk>/', request_book, name='request-book'),
    # Members
    path('members/', members_list, name='list-members'),
    path('members/<int:pk>/', member_info, name='member-detail'),
    path('members/<int:pk>/report/', member_report, name='member-report')
]

lms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authentication.views import login_or_register

urlpatterns = [
    path('', login_or_register, name='login-or-register'),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls')),
    path('qr/', include('qrmanager.urls')),
    path('admin/', admin.site.urls)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class LMSUser(AbstractUser):
    is_librarian = models.BooleanField(default=False)

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import LMSUser


class LMSUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=40, label='First Name')
    last_name = forms.CharField(
        max_length=40, label='Last Name')
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = LMSUser

    def save(self, commit=True):
        user = super(LMSUserCreationForm, self).save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

from .decorators import redirect_authenticated
from .forms import LMSUserCreationForm


@redirect_authenticated
def login_or_register(request):
    return render(request, 'authentication/login_or_register.html', {})


def register_user(request, is_librarian):
    form = LMSUserCreationForm(request.POST or None)

    context = {
        'form': form,
        'user_type': 'Librarian' if is_librarian else 'Member'
    }

    if request.method == 'POST':
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.is_librarian = is_librarian
            new_user.save()
            login(request, new_user)
            return redirect('dashboard:home')

    return render(request, 'authentication/register.html', context)


@redirect_authenticated
def register_librarian(request):
    return register_user(request, True)


@redirect_authenticated
def register_member(request):
    return register_user(request, False)


@redirect_authenticated
def login_user(request):
    form = AuthenticationForm(data=request.POST or None)
    redirect_url = request.GET.get('next') or 'dashboard:home'

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(redirect_url)

    return render(request, 'authentication/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('login-or-register')

authentication/templates/authentication/login.html
{% load static %} {% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Grantha LMS | Login</title>
        <link
            rel="icon"
            type="image/png"
            href="{% static 'custom/images/favicon.ico' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'bootstrap-5.3.0-dist/css/bootstrap.min.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/fontawesome.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/solid.css' %}"
        />
        <link rel="stylesheet" href="{% static 'custom/css/shared.css' %}" />
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container mb-4">
            <div class="row my-5">
                <div class="col col-md-8 mx-auto">
                    <div class="border border-dark rounded">
                        <h2 class="text-white bg-dark px-3 py-4 mb-3">
                            <i class="fa fa-user"></i> User Login
                        </h2>
                        <div class="px-4">
                            <form method="post" class="mb-3">
                                {% csrf_token %} {{ form|crispy }}
                                <button
                                    type="submit"
                                    class="btn btn-dark mx-auto"
                                >
                                    Login
                                </button>
                            </form>
                            <p>
                                No account? You can
                                <a
                                    href="{% url 'authentication:register-librarian' %}"
                                    class="link-dark"
                                    >Register as Librarian</a
                                >
                                or
                                <a
                                    href="{% url 'authentication:register-member' %}"
                                    class="link-dark"
                                    >Register as Member</a
                                >
                                of the library.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

authentication/templates/authentication/login_or_register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Grantha LMS | Welcome</title>
        <link
            rel="icon"
            type="image/png"
            href="{% static 'custom/images/favicon.ico' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'bootstrap-5.3.0-dist/css/bootstrap.min.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/fontawesome.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/solid.css' %}"
        />
        <link rel="stylesheet" href="{% static 'custom/css/landing.css' %}" />
    </head>
    <body>
        <!-- Hero Section -->
        <section id="hero">
            <div
                class="container d-flex flex-column justify-content-center align-items-center text-center text-white"
                id="hero-content"
            >
                <h1 class="mb-4 display-1">Welcome to Grantha LMS!</h1>
                <p>
                    Get started by registering or logging in. Or, continue
                    anonymously.
                </p>
                <div
                    class="d-flex flex-column align-items-md-baseline flex-md-row"
                >
                    <a
                        href="{% url 'authentication:register-librarian' %}"
                        role="button"
                        class="btn btn-dark mb-3 my-md-0 me-md-3"
                        >Register as Librarian</a
                    >
                    <a
                        href="{% url 'authentication:register-member' %}"
                        role="button"
                        class="btn btn-dark mb-3 my-md-0 me-md-3"
                        >Register as Member</a
                    >
                    <a
                        href="{% url 'authentication:login' %}"
                        role="button"
                        class="btn btn-secondary mb-3 my-md-0 me-md-3"
                        >Login</a
                    >
                </div>
                <a
                    href="{% url 'dashboard:home' %}"
                    role="button"
                    class="btn btn-success rounded-pill p-3 mt-4"
                    >Continue to home <i class="fa fa-arrow-right"></i
                ></a>
                <a
                    href="#features"
                    class="link-light link-underline-opacity-0 position-absolute bottom-0 start-50 translate-middle my-4"
                    id="features-link"
                >
                    <div class="d-flex flex-column align-items-center">
                        <p class="mb-0">Features</p>
                        <span><i class="fa fa-angles-down"></i></span>
                    </div>
                </a>
            </div>
            <div class="curve-bottom">
                <svg
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 1200 120"
                    preserveAspectRatio="none"
                >
                    <path
                        d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z"
                        class="shape-fill"
                    ></path>
                </svg>
            </div>
        </section>

        <!-- Features Section -->
        <section class="container p-4" id="features">
            <h1 class="display-4">Features</h1>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 py-4">
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-book-open"></i>
                    </h3>
                    <div>
                        <h3>Book Records</h3>
                        <p class="text-secondary">
                            Author, Publisher and Category records associated
                            with books maintained separately.
                        </p>
                    </div>
                </div>
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-arrows-left-right"></i>
                    </h3>
                    <div>
                        <h3>Issues Tracking</h3>
                        <p class="text-secondary">
                            Record of issues of individual copies with returned
                            and overdue status is kept.
                        </p>
                    </div>
                </div>
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-hand"></i>
                    </h3>
                    <div>
                        <h3>Book Requests</h3>
                        <p class="text-secondary">
                            Ability to request books from selection of books
                            currently available in library.
                        </p>
                    </div>
                </div>
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-file-pdf"></i>
                    </h3>
                    <div>
                        <h3>Report Generation</h3>
                        <p class="text-secondary">
                            Report on individual members with their issues, book
                            requests and late fine history.
                        </p>
                    </div>
                </div>
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-qrcode"></i>
                    </h3>
                    <div>
                        <h3>QR Features</h3>
                        <p class="text-secondary">
                            Generation and processing of QR code as member ID.
                        </p>
                    </div>
                </div>
                <div class="col d-flex">
                    <h3 class="me-3">
                        <i class="fa fa-mobile"></i>
                    </h3>
                    <div>
                        <h3>Mobile Friendly</h3>
                        <p class="text-secondary">
                            Completely responsive layout for comfortable usage
                            on smaller screens.
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

authentication/templates/authentication/register.html
{% load static %} {% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Grantha LMS | Register</title>
        <link
            rel="icon"
            type="image/png"
            href="{% static 'custom/images/favicon.ico' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'bootstrap-5.3.0-dist/css/bootstrap.min.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/fontawesome.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/solid.css' %}"
        />
        <link rel="stylesheet" href="{% static 'custom/css/shared.css' %}" />
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container mb-4">
            <div class="row my-5">
                <div class="col col-md-8 mx-auto">
                    <div class="border border-dark rounded">
                        <h2 class="text-white bg-dark px-3 py-4 mb-3">
                            <i class="fa fa-user-plus"></i> {{ user_type }}
                            Registration
                        </h2>
                        <div class="px-4">
                            <form method="post" class="mb-3">
                                {% csrf_token %} {{ form|crispy }}
                                <button
                                    type="submit"
                                    class="btn btn-dark mx-auto"
                                >
                                    Register
                                </button>
                            </form>
                            <p>
                                Already have an account? Proceed to
                                <a
                                    href="{% url 'authentication:login' %}"
                                    class="link-dark"
                                    >Log In</a
                                >
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>