dashboard/urls.py
from django.urls import path

from .views.general import home, browse_books
from .views.author import AuthorCreateView, list_authors, AuthorUpdateView, delete_author
from .views.publisher import PublisherCreateView, list_publishers, PublisherUpdateView, delete_publisher
from .views.category import CategoryCreateView, list_categories, CategoryUpdateView, delete_category
from .views.book import create_book, list_books, book_detail, update_book, delete_book
from .views.issue import issue_book, list_issues, return_issued_book
from .views.fine import list_fines
from .views.book_request import request_book, list_book_requests
from .views.member import members_list, member_info, member_report

app_name = 'dashboard'
urlpatterns = [
    # Dashboard home
    path('home/', home, name='home'),
    path('browse/', browse_books, name='browse'),
    # Authors
    path('authors/', list_authors, name='list-authors'),
    path('authors/new/', AuthorCreateView.as_view(), name='create-author'),
    path('authors/<int:pk>/update/',
         AuthorUpdateView.as_view(), name='update-author'),
    path('authors/<int:pk>/delete/',
         delete_author, name='delete-author'),
    # Publishers
    path('publishers/', list_publishers, name='list-publishers'),
    path('publishers/new/', PublisherCreateView.as_view(), name='create-publisher'),
    path('publishers/<int:pk>/update/',
         PublisherUpdateView.as_view(), name='update-publisher'),
    path('publishers/<int:pk>/delete/',
         delete_publisher, name='delete-publisher'),
    # Categories
    path('categories/', list_categories, name='list-categories'),
    path('categories/new/', CategoryCreateView.as_view(), name='create-category'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='update-category'),
    path('categories/<int:pk>/delete/',
         delete_category, name='delete-category'),
    # Books
    path('books/', list_books, name='list-books'),
    path('books/new/', create_book, name='create-book'),
    path('books/<int:pk>/', book_detail, name='book-detail'),
    path('books/<int:pk>/update/', update_book, name='update-book'),
    path('books/<int:pk>/delete/', delete_book, name='delete-book'),
    # Issue
    path('issues/', list_issues, name='list-issues'),
    path('issues/new/', issue_book, name='create-issue'),
    path('issues/<int:pk>/return/', return_issued_book, name='return-issued'),
    # Fines
    path('fines/', list_fines, name='list-fines'),
    # Book Requests
    path('books/requests/', list_book_requests, name='book-requests'),
    path('books/requests/<int:pk>/', request_book, name='request-book'),
    # Members
    path('members/', members_list, name='list-members'),
    path('members/<int:pk>/', member_info, name='member-detail'),
    path('members/<int:pk>/report/', member_report, name='member-report')
]

lms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authentication.views import login_or_register

urlpatterns = [
    path('', login_or_register, name='login-or-register'),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls')),
    path('qr/', include('qrmanager.urls')),
    path('admin/', admin.site.urls)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url='authentication:login-or-register')
def home(request):
    return render(request, 'dashboard/home.html', {})

dashboard/views/author.py
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import ProtectedError

from authentication.decorators import only_librarians

from .general import list_card_items, LibrarianView
from ..mixins import EditMixin
from ..models import Author


class AuthorCreateView(EditMixin, LibrarianView, CreateView):
    model = Author

    def get_context_data(self, **kwargs):
        return super().get_context_data('Author', **kwargs)


def list_authors(request):
    return list_card_items(request, Author, 'dashboard/author_cards.html', 'dashboard/list_authors.html', 'author')


class AuthorUpdateView(EditMixin, LibrarianView, UpdateView):
    model = Author

    def get_context_data(self, **kwargs):
        return super().get_context_data('Author', **kwargs)


@login_required
@only_librarians
def delete_author(request, pk):
    author = get_object_or_404(Author, id=pk)

    if request.method == 'POST':
        try:
            author.delete()
            return redirect(reverse_lazy('dashboard:list-authors'))
        except ProtectedError:
            messages.error(
                request, f'Author {author} is referenced in book record.')
            return redirect('dashboard:list-authors')

    context = {
        'item_type': 'Author',
        'object': author
    }

    return render(request, 'dashboard/generic_delete.html', context)

dashboard/views/book.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db.models import ProtectedError

from authentication.decorators import only_librarians

from ..models import Book, BookAuthor, BookCategory, BookCopy
from ..forms.book_forms import BookCreateForm, BookUpdateForm
from ..utils import has_pending_requests, add_book_attributes


@login_required
@only_librarians
def create_book(request):
    form = BookCreateForm(request.POST or None)

    context = {
        'form': form,
        'item_type': 'Book'
    }

    if request.method == 'POST':
        if form.is_valid():
            form.create()
            return redirect('dashboard:list-books')

    return render(request, 'dashboard/generic_edit.html', context)


def list_books(request):
    # Get search parameter and query text
    query_params = request.GET
    p_filter = query_params.get('filter')
    p_query = query_params.get('query')

    # Filter results from queryset
    qs = Book.objects.all()
    if p_filter and p_query:
        if p_filter == 'title':
            qs = qs.filter(title__icontains=p_query)
        if p_filter == 'publisher' and len(qs) > 0:
            qs = qs.filter(publisher__name__icontains=p_query)
        if p_filter == 'isbn' and len(qs) > 0:
            qs = qs.filter(isbn__exact=p_query.strip())
        if p_filter == 'author' and len(qs) > 0:
            book_author_rels = BookAuthor.objects.filter(
                author__name__icontains=p_query)
            titles = [ba.book.title for ba in book_author_rels]
            qs = qs.filter(title__in=titles)
        if p_filter == 'category' and len(qs) > 0:
            book_category_rels = BookCategory.objects.filter(
                category__name__icontains=p_query)
            titles = [bc.book.title for bc in book_category_rels]
            qs = qs.filter(title__in=titles)

    # Add additional attributes to books in queryset
    books = []
    for book in qs:
        add_book_attributes(book, request)
        books.append(book)

    context = {
        'books': books,
        'p_filter': p_filter,
        'p_query': p_query,
    }

    return render(request, 'dashboard/list_books.html', context)


def book_detail(request, pk):
    book = get_object_or_404(Book, id=pk)

    is_requested = False
    if request.user.is_authenticated:
        is_requested = has_pending_requests(book, request.user)
    is_available = BookCopy.objects.filter(
        book=book, is_available=True).count() > 0

    book_author_rels = BookAuthor.objects.filter(
        book=book).select_related('author')
    book_category_rels = BookCategory.objects.filter(
        book=book).select_related('category')

    context = {
        'book': book,
        'is_requested': is_requested,
        'is_available': is_available,
        'authors': [ba.author.name for ba in book_author_rels],
        'categories': [bc.category.name for bc in book_category_rels],
    }

    return render(request, 'dashboard/book_detail.html', context)


@login_required
@only_librarians
def update_book(request, pk):
    book = get_object_or_404(Book, id=pk)

    book_author_rels = BookAuthor.objects.select_related(
        'author').filter(book=book)
    book_category_rels = BookCategory.objects.select_related(
        'category').filter(book=book)

    form = BookUpdateForm(
        request.POST or None, book=book,
        book_author_rels=book_author_rels, book_category_rels=book_category_rels,
        initial={
            'title': book.title,
            'quantity': BookCopy.objects.filter(book=book).count(),
            'isbn': book.isbn,
            'authors': [ba.author for ba in book_author_rels],
            'publisher': book.publisher,
            'categories': [bc.category for bc in book_category_rels]
        })

    context = {
        'form': form,
        'item_type': 'Book'
    }

    if request.method == 'POST':
        if form.is_valid():
            if form.has_changed():
                form.update()
            return redirect('dashboard:list-books')

    return render(request, 'dashboard/generic_edit.html', context)


@login_required
@only_librarians
def delete_book(request, pk):
    book = get_object_or_404(Book, id=pk)

    if request.method == 'POST':
        if has_pending_requests(book):
            messages.error(
                request, 'Only books with all requests fulfilled can be deleted.')
            return redirect('dashboard:list-books')
        try:
            book.delete()
            return redirect(reverse_lazy('dashboard:list-books'))
        except ProtectedError:
            messages.error(
                request, 'Only books with no copies can be deleted.')
            return redirect('dashboard:list-books')

    context = {
        'item_type': 'Book',
        'object': book
    }

    return render(request, 'dashboard/generic_delete.html', context)

dashboard/views/book_request.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from datetime import date

from authentication.decorators import only_members, only_librarians

from ..models import Book, Request, BookCopy
from ..utils import has_pending_requests


@login_required
@only_members
def request_book(request, pk):
    book = get_object_or_404(Book, id=pk)

    is_available = BookCopy.objects.filter(
        book=book, is_available=True).count() > 0

    if request.method == 'POST':
        if not is_available:
            messages.error(
                request, f'Book "{book}" is not available in Library.')
        elif has_pending_requests(book, request.user):
            messages.warning(
                request, f'Request for book "{book}" is already pending.')
        else:
            Request.objects.create(
                book=book, member=request.user, request_date=date.today(), is_fulfilled=False)
        return redirect('dashboard:list-books')

    return render(request, 'dashboard/request_book.html', {'book': book})


@login_required
@only_librarians
def list_book_requests(request):
    query_params = request.GET
    p_title = query_params.get('query')

    book_requests = Request.objects.order_by('is_fulfilled')
    if p_title:
        book_requests = book_requests.filter(book__title__icontains=p_title)

    context = {
        'object_list': book_requests,
        'search_placeholder': 'Search by book title',
        'query_text': p_title
    }

    return render(request, 'dashboard/list_book_requests.html', context)

dashboard/views/category.py
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import ProtectedError

from authentication.decorators import only_librarians

from .general import list_card_items, LibrarianView
from ..mixins import EditMixin
from ..models import Category


class CategoryCreateView(EditMixin, LibrarianView, CreateView):
    model = Category

    def get_context_data(self, **kwargs):
        return super().get_context_data('Category', **kwargs)


def list_categories(request):
    return list_card_items(request, Category, 'dashboard/category_cards.html', 'dashboard/list_categories.html', 'category')


class CategoryUpdateView(EditMixin, LibrarianView, UpdateView):
    model = Category

    def get_context_data(self, **kwargs):
        return super().get_context_data('Category', **kwargs)


@login_required
@only_librarians
def delete_category(request, pk):
    category = get_object_or_404(Category, id=pk)

    if request.method == 'POST':
        try:
            category.delete()
            return redirect(reverse_lazy('dashboard:list-categories'))
        except ProtectedError:
            messages.error(
                request, f'Category {category} is referenced in book record.')
            return redirect('dashboard:list-categories')

    context = {
        'item_type': 'Category',
        'object': category
    }

    return render(request, 'dashboard/generic_delete.html', context)

dashboard/views/fine.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from authentication.decorators import only_librarians

from ..models import LateFine


@login_required
@only_librarians
def list_fines(request):
    query_params = request.GET
    p_title = query_params.get('query')

    fines = LateFine.objects.order_by('-fined_date')
    if p_title:
        fines = fines.filter(book_copy__book__title__icontains=p_title)

    context = {
        'object_list': fines,
        'search_placeholder': 'Search by book title',
        'query_text': p_title
    }

    return render(request, 'dashboard/list_fines.html', context)

dashboard/views/issue.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from datetime import date

from authentication.decorators import only_librarians

from ..models import Issue, LateFine, Request
from ..forms.issue_forms import IssueCreateForm
from ..utils import add_is_due


@login_required
@only_librarians
def issue_book(request):
    book_request = None
    book_request_id = request.GET.get('rid', None)
    if book_request_id:
        qs = Request.objects.filter(is_fulfilled=False)
        try:
            book_request = get_object_or_404(qs, id=book_request_id)
        except ValueError:
            messages.error(request, f'Invalid rid {book_request_id}.')
            return redirect('dashboard:list-issues')

    if request.method == 'GET':
        form = IssueCreateForm(
            initial={
                'book': book_request.book,
                'member': book_request.member
            }
        ) if book_request else IssueCreateForm()

    if request.method == 'POST':
        form = IssueCreateForm(request.POST)
        if form.is_valid():
            form.create()
            if book_request:
                book_request.is_fulfilled = True
                book_request.save()
            return redirect('dashboard:list-issues')

    return render(request, 'dashboard/create_issue.html', {'form': form})


@login_required
@only_librarians
def list_issues(request):
    query_params = request.GET
    p_title = query_params.get('query')

    issues = Issue.objects.order_by('due_date')
    if p_title:
        issues = issues.filter(book_copy__book__title__icontains=p_title)

    add_is_due(issues)

    context = {
        'issues': issues,
        'search_placeholder': 'Search by book title',
        'query_text': p_title
    }

    return render(request, 'dashboard/list_issues.html', context)


@login_required
@only_librarians
def return_issued_book(request, pk):
    issue = get_object_or_404(Issue, id=pk)

    if issue.returned_date:
        messages.warning(request, 'Issue has already been returned prior.')
        return redirect('dashboard:list-issues')

    due_days = 0
    fine_amount = 0
    due_date = issue.due_date
    today = date.today()
    if due_date > today:
        status = 'Not due'
    else:
        due_days = abs(today - due_date).days
        if due_days == 0:
            status = 'Due Today'
        else:
            fine_amount = due_days * issue.late_fine_rate
            status = 'Overdue'

    context = {
        'issue': issue,
        'status': status,
        'due_days': due_days,
        'fine_amount': fine_amount
    }

    if request.method == 'POST':
        if due_days:
            LateFine.objects.create(
                book_copy=issue.book_copy,
                member=issue.member,
                late_days=due_days,
                amount=fine_amount,
                fined_date=today
            )

        issue.book_copy.is_available = True
        issue.book_copy.save()
        issue.returned_date = today
        issue.save()
        return redirect('dashboard:list-issues')

    return render(request, 'dashboard/return_issued.html', context)

dashboard/templates/dashboard/book_detail.html
{% extends 'base.html' %} {% block content %}
<div class="d-flex align-items-center">
    <h2 class="my-3 me-3">{{ book.title }}</h2>
    {% if is_requested %}
    <span class="badge text-bg-warning">Requested</span>
    {% elif is_available %}
    <span class="badge text-bg-success">Available</span>
    {% else %}
    <span class="badge text-bg-danger">Not Available</span>
    {% endif %}
</div>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3 fw-bold">ISBN</div>
            <div class="col-sm-9 text-secondary">{{ book.isbn }}</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-3 fw-bold">Publisher</div>
            <div class="col-sm-9 text-secondary">{{ book.publisher }}</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-3 fw-bold">Author(s)</div>
            <div class="col-sm-9 text-secondary">
                {% if authors %}
                <!-- Display authors joined by comma -->
                {{ authors|join:', ' }} {% else %}
                <!-- Display not available -->
                None {% endif %}
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-3 fw-bold">Categories</div>
            <div class="col-sm-9 text-secondary">
                {% if categories %}
                <!-- Display categories joined by comma -->
                {{ categories|join:', ' }} {% else %}
                <!-- Display not available -->
                None {% endif %}
            </div>
        </div>
    </div>
</div>
{% if not user.is_authenticated and is_available %}
<a href="{% url 'dashboard:request-book' book.id %}" class="btn btn-dark mt-3"
    >Request book</a
>
{% elif not user.is_librarian and not is_requested and is_available %}
<a href="{% url 'dashboard:request-book' book.id %}" class="btn btn-dark mt-3"
    >Request book</a
>
{% endif %} {% endblock %}

dashboard/templates/dashboard/librarian_home.html
{% extends 'base.html' %} {% block content %}
<h1 class="mt-3 display-6">Welcome, {{ user }}!</h1>

<!-- Stats -->
<div class="row row-cols-2 row-cols-lg-4 g-3 mt-2">
    <div class="col">
        <div class="card border-dark h-100 position-relative">
            <div class="card-body text-center">
                <h5 class="card-title fs-3 fw-bold">{{ total_books_count }}</h5>
                <p class="card-text fs-5">Titles</p>
            </div>
            <span
                class="position-absolute top-0 start-50 translate-middle badge text-bg-success rounded-pill"
                >{{ available_books_count }} available</span
            >
        </div>
    </div>
    <div class="col">
        <div class="card border-dark h-100 position-relative">
            <div class="card-body text-center">
                <h5 class="card-title fs-3 fw-bold">{{ issues_count }}</h5>
                <p class="card-text fs-5">Current Issues</p>
            </div>
            <span
                class="position-absolute top-0 start-50 translate-middle badge text-bg-danger rounded-pill"
                >{{ overdue_count }} overdue</span
            >
        </div>
    </div>
    <div class="col">
        <div class="card border-dark h-100">
            <div class="card-body text-center">
                <h5 class="card-title fs-3 fw-bold">{{ requests_count }}</h5>
                <p class="card-text fs-5">Pending Requests</p>
            </div>
        </div>
    </div>
</div>

<!-- Latest Issues -->
<h2 class="my-3">Issued Copies</h2>
{% if issues %}
<p>Top book issues withheld by members sorted by due date:</p>
<div class="table-responsive text-nowrap">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Book</th>
                <th scope="col">Copy #</th>
                <th scope="col">Member</th>
                <th scope="col">Issue Date</th>
                <th scope="col">Due Date</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for issue in issues %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                {% if issue.book_copy %}
                <td>{{ issue.book_copy.book }}</td>
                <td>{{ issue.book_copy.id }}</td>
                {% else %}
                <td>N/A</td>
                <td>N/A</td>
                {% endif %}
                <td>{{ issue.member }}</td>
                <td>{{ issue.issue_date }}</td>
                <td>{{ issue.due_date }}</td>
                <td>
                    {% if issue.is_due %}
                    <span class="badge rounded-pill text-bg-danger"
                        >Overdue</span
                    >
                    {% else %}
                    <span class="badge rounded-pill text-bg-primary"
                        >Issued</span
                    >
                    {% endif %}
                </td>
                <td>
                    <a
                        href="{% url 'dashboard:return-issued' issue.id %}"
                        class="link-underline link-underline-opacity-0 link-primary"
                        >Return to Library</a
                    >
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>Sorry, no issues found with books withheld by members.</p>
{% endif %}

<!-- Pending Requests -->
<h2 class="my-3">Pending Requests</h2>
{% if requests %}
<p>Top pending book requests sorted by request date:</p>
<div class="table-responsive text-nowrap">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Book</th>
                <th scope="col">Member</th>
                <th scope="col">Requested On</th>
                <th class="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for req in requests %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ req.book }}</td>
                <td>{{ req.member }}</td>
                <td>{{ req.request_date }}</td>
                <td>
                    <a
                        href="{% url 'dashboard:create-issue' %}?rid={{ req.id }}"
                        class="link-underline link-underline-opacity-0 link-primary"
                        >Fulfill request</a
                    >
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>Sorry, no requests seem to be pending.</p>
{% endif %} {% endblock %}

dashboard/templates/dashboard/list_authors.html
{% extends 'base.html' %} {% block content %}
<h2 class="my-3">Authors</h2>
{% include 'dashboard/search_form.html' %}
<div class="table-responsive text-nowrap">
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Name</th>
                <th scope="col">Contact No</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Date of birth</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for author in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ author.name }}</td>
                <td>{{ author.contact_no }}</td>
                <td>{{ author.email }}</td>
                <td>{{ author.address }}</td>
                <td>{{ author.date_of_birth }}</td>
                <td>
                    <a
                        href="{% url 'dashboard:update-author' author.id %}"
                        class="link-underline link-underline-opacity-0 link-success mx-1"
                        ><i class="fa fa-pen-to-square fs-5"></i
                    ></a>
                    <a
                        href="{% url 'dashboard:delete-author' author.id %}"
                        class="link-underline link-underline-opacity-0 link-danger mx-1"
                        ><i class="fa fa-trash fs-5"></i
                    ></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>Sorry, no authors found.</p>
    {% endif %}
</div>
<a
    class="btn btn-success"
    href="{% url 'dashboard:create-author' %}"
    role="button"
    >Add Author</a
>
{% endblock %}

dashboard/templates/dashboard/list_book_requests.html
{% extends 'base.html' %} {% block content %}
<h2 class="my-3">Book Requests</h2>
{% include 'dashboard/search_form.html' %} {% if object_list %}
<div class="table-responsive text-nowrap">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Book</th>
                <th scope="col">Member</th>
                <th scope="col">Requested On</th>
                <th scope="col">Status</th>
                <th class="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for book_request in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                {% if book_request.book %}
                <td>{{ book_request.book }}</td>
                {% else %}
                <td>N/A</td>
                {% endif %}
                <td>{{ book_request.member }}</td>
                <td>{{ book_request.request_date }}</td>
                <td>
                    {% if book_request.is_fulfilled %}
                    <span class="badge rounded-pill text-bg-success"
                        >Issued</span
                    >
                    {% else %}
                    <span class="badge rounded-pill text-bg-warning"
                        >Pending</span
                    >
                    {% endif %}
                </td>
                <td>
                    {% if book_request.is_fulfilled %} --- {% else %}
                    <a
                        href="{% url 'dashboard:create-issue' %}?rid={{ book_request.id }}"
                        class="link-underline link-underline-opacity-0 link-primary"
                        >Fulfill request</a
                    >
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>Sorry, no book requests found.</p>
    {% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard/list_categories.html
{% extends 'base.html' %} {% block content %}
<h2 class="my-3">Categories</h2>
{% include 'dashboard/search_form.html' %}
<div class="table-responsive text-nowrap">
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for category in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>
                    <a
                        href="{% url 'dashboard:update-category' category.id %}"
                        class="link-underline link-underline-opacity-0 link-success mx-1"
                        ><i class="fa fa-pen-to-square fs-5"></i
                    ></a>
                    <a
                        href="{% url 'dashboard:delete-category' category.id %}"
                        class="link-underline link-underline-opacity-0 link-danger mx-1"
                        ><i class="fa fa-trash fs-5"></i
                    ></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>Sorry, no categories found.</p>
    {% endif %}
</div>
<a
    class="btn btn-success"
    href="{% url 'dashboard:create-category' %}"
    role="button"
    >Add Category</a
>
{% endblock %}

dashboard/templates/dashboard/list_publishers.html
{% extends 'base.html' %} {% block content %}
<h2 class="my-3">Publishers</h2>
{% include 'dashboard/search_form.html' %}
<div class="table-responsive text-nowrap">
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Name</th>
                <th scope="col">Contact No</th>
                <th scope="col">Address</th>
                <th scope="col">Email</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for publisher in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ publisher.name }}</td>
                <td>{{ publisher.contact_no }}</td>
                <td>{{ publisher.address }}</td>
                <td>{{ publisher.email }}</td>
                <td>
                    <a
                        href="{% url 'dashboard:update-publisher' publisher.id %}"
                        class="link-underline link-underline-opacity-0 link-success mx-1"
                        ><i class="fa fa-pen-to-square fs-5"></i
                    ></a>
                    <a
                        href="{% url 'dashboard:delete-publisher' publisher.id %}"
                        class="link-underline link-underline-opacity-0 link-danger mx-1"
                        ><i class="fa fa-trash fs-5"></i
                    ></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>Sorry, no publishers found.</p>
    {% endif %}
</div>
<a
    class="btn btn-success"
    href="{% url 'dashboard:create-publisher' %}"
    role="button"
    >Add Publisher</a
>
{% endblock %}