authentication/urls.py
from django.urls import path

from .views import (register_librarian, register_member,
                    login_user, logout_user)

app_name = 'authentication'
urlpatterns = [
    path('register-librarian/', register_librarian, name='register-librarian'),
    path('register-member/', register_member, name='register-member'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

dashboard/urls.py
from django.urls import path

from .views.general import home, browse_books
from .views.author import AuthorCreateView, list_authors, AuthorUpdateView, delete_author
from .views.publisher import PublisherCreateView, list_publishers, PublisherUpdateView, delete_publisher
from .views.category import CategoryCreateView, list_categories, CategoryUpdateView, delete_category
from .views.book import create_book, list_books, book_detail, update_book, delete_book
from .views.issue import issue_book, list_issues, return_issued_book
from .views.fine import list_fines
from .views.book_request import request_book, list_book_requests
from .views.member import members_list, member_info, member_report

app_name = 'dashboard'
urlpatterns = [
    # Dashboard home
    path('home/', home, name='home'),
    path('browse/', browse_books, name='browse'),
    # Authors
    path('authors/', list_authors, name='list-authors'),
    path('authors/new/', AuthorCreateView.as_view(), name='create-author'),
    path('authors/<int:pk>/update/',
         AuthorUpdateView.as_view(), name='update-author'),
    path('authors/<int:pk>/delete/',
         delete_author, name='delete-author'),
    # Publishers
    path('publishers/', list_publishers, name='list-publishers'),
    path('publishers/new/', PublisherCreateView.as_view(), name='create-publisher'),
    path('publishers/<int:pk>/update/',
         PublisherUpdateView.as_view(), name='update-publisher'),
    path('publishers/<int:pk>/delete/',
         delete_publisher, name='delete-publisher'),
    # Categories
    path('categories/', list_categories, name='list-categories'),
    path('categories/new/', CategoryCreateView.as_view(), name='create-category'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='update-category'),
    path('categories/<int:pk>/delete/',
         delete_category, name='delete-category'),
    # Books
    path('books/', list_books, name='list-books'),
    path('books/new/', create_book, name='create-book'),
    path('books/<int:pk>/', book_detail, name='book-detail'),
    path('books/<int:pk>/update/', update_book, name='update-book'),
    path('books/<int:pk>/delete/', delete_book, name='delete-book'),
    # Issue
    path('issues/', list_issues, name='list-issues'),
    path('issues/new/', issue_book, name='create-issue'),
    path('issues/<int:pk>/return/', return_issued_book, name='return-issued'),
    # Fines
    path('fines/', list_fines, name='list-fines'),
    # Book Requests
    path('books/requests/', list_book_requests, name='book-requests'),
    path('books/requests/<int:pk>/', request_book, name='request-book'),
    # Members
    path('members/', members_list, name='list-members'),
    path('members/<int:pk>/', member_info, name='member-detail'),
    path('members/<int:pk>/report/', member_report, name='member-report')
]

lms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from authentication.views import login_or_register

urlpatterns = [
    path('', login_or_register, name='login-or-register'),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls')),
    path('qr/', include('qrmanager.urls')),
    path('admin/', admin.site.urls)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qrmanager/urls.py
from django.urls import path

from .views import download_qr, upload_qr

app_name = 'qrmanager'
urlpatterns = [
    path('download/', download_qr, name='download-qr'),
    path('upload/', upload_qr, name='upload-qr')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Grantha LMS</title>
        <link
            rel="icon"
            type="image/png"
            href="{% static 'custom/images/favicon.ico' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'bootstrap-5.3.0-dist/css/bootstrap.min.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/fontawesome.css' %}"
        />
        <link
            rel="stylesheet"
            href="{% static 'fontawesomefree/css/solid.css' %}"
        />
        <link rel="stylesheet" href="{% static 'custom/css/shared.css' %}" />
        <link rel="stylesheet" href="{% static 'custom/css/messages.css' %}" />
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="d-flex">
            {% include 'sidebar.html' %}
            <div class="container mb-4" id="content-div">
                {% block content %}{% endblock %}
            </div>
        </div>
        {% if messages %}
        <div id="dj-messages">
            {% for message in messages %} {% if message.tags == 'error' %}
            <div
                class="alert alert-danger alert-dismissable fade show"
                role="alert"
            >
                {{ message }}
            </div>
            {% else %}
            <div
                class="alert alert-{{ message.tags }} alert-dismissable fade show"
                role="alert"
            >
                {{ message }}
            </div>
            {% endif %} {% endfor %}
        </div>
        {% endif %}
        <script src="{% static 'bootstrap-5.3.0-dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'custom/js/alertDismiss.js' %}"></script>
    </body>
</html>

templates/librarian_navitems.html
<ul class="nav nav-pills flex-column">
    <li class="nav-item">
        <a href="{% url 'dashboard:home' %}" class="nav-link text-white">
            <i class="fa fa-home"></i> Home
        </a>
    </li>
    <hr />
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-authors' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-pen-nib"></i> Authors
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-publishers' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-print"></i> Publishers
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-categories' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-tag"></i> Categories
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'dashboard:list-books' %}" class="nav-link text-white">
            <i class="fa fa-book"></i> Books
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'dashboard:list-issues' %}" class="nav-link text-white">
            <i class="fa fa-arrows-left-right"></i>
            Issues
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'dashboard:list-fines' %}" class="nav-link text-white">
            <i class="fa fa-rupee-sign"></i> Late Fines
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:book-requests' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-hand"></i> Book Requests
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-members' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-users"></i> Members
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'qrmanager:upload-qr' %}" class="nav-link text-white">
            <i class="fa fa-qrcode"></i> QR Upload
        </a>
    </li>
</ul>

templates/member_navitems.html
<ul class="nav nav-pills flex-column">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a href="{% url 'dashboard:home' %}" class="nav-link text-white">
            <i class="fa fa-home"></i> Home
        </a>
    </li>
    <hr />
    {% endif %}
    <li class="nav-item">
        <a href="{% url 'dashboard:browse' %}" class="nav-link text-white">
            <i class="fa fa-globe"></i> Browse
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-authors' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-pen-nib"></i> Authors
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-publishers' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-print"></i> Publishers
        </a>
    </li>
    <li class="nav-item">
        <a
            href="{% url 'dashboard:list-categories' %}"
            class="nav-link text-white"
        >
            <i class="fa fa-tag"></i> Categories
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'dashboard:list-books' %}" class="nav-link text-white">
            <i class="fa fa-book"></i> Books
        </a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a href="{% url 'qrmanager:download-qr' %}" class="nav-link text-white">
            <i class="fa fa-qrcode"></i> QR Download
        </a>
    </li>
    {% endif %}
</ul>

templates/navbar.html
{% load static %} {% if not request.path == '/' %}
<nav class="navbar navbar-dark bg-dark sticky-top">
    <div class="container-fluid position-relative">
        <button
            class="navbar-toggler position-absolute d-lg-none"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasResponsive"
            aria-controls="offcanvasResponsive"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <a
            class="navbar-brand w-100 text-center fs-4 me-0"
            href="{% url 'dashboard:home' %}"
            ><img
                src="{% static 'custom/images/grantha.svg' %}"
                alt="grantha-logo"
                id="grantha-logo"
        /></a>
    </div>
</nav>
{% endif %}

templates/sidebar.html
{% if not request.path == '/' and 'auth/' not in request.path %}
<div
    class="offcanvas-lg offcanvas-start text-bg-dark sidebar"
    tabindex="-1"
    id="offcanvasResponsive"
    aria-labelledby="offcanvasResponsiveLabel"
>
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasResponsiveLabel">
            Quick Links
        </h5>
        <button
            type="button"
            class="btn-close btn-close-white"
            data-bs-dismiss="offcanvas"
            data-bs-target="#offcanvasResponsive"
            aria-label="Close"
        ></button>
    </div>
    <div class="offcanvas-body d-flex flex-column h-100">
        {% if not user.is_authenticated %}
        <!-- Include general nav items -->
        {% include 'member_navitems.html' %}
        <hr class="mt-auto mb-0" />
        <ul class="nav nav-pills py-2">
            <li class="nav-item">
                <a
                    href="{% url 'login-or-register' %}"
                    class="nav-link text-light"
                >
                    <i class="fa fa-right-to-bracket"></i>
                    Login/Register
                </a>
            </li>
        </ul>
        {% else %}
        <!-- Include authenticated nav items -->
        {% if user.is_librarian %}
        <!-- Include librarian nav items -->
        {% include 'librarian_navitems.html' %} {% else %}
        <!-- Include member nav items -->
        {% include 'member_navitems.html' %} {% endif %}
        <hr class="mt-auto mb-0" />
        <ul class="nav nav-pills py-2">
            <li class="nav-item">
                <a
                    href="{% url 'authentication:logout' %}"
                    class="nav-link text-light"
                >
                    <i class="fa fa-right-from-bracket"></i>
                    Logout
                </a>
            </li>
        </ul>
        {% endif %}
    </div>
</div>
{% endif %}